---
title: "Lecture 10 - Making choices and some practice"
output: 
  beamer_presentation:
    fig_caption: false
    includes:
      in_header: ../mypreamble.tex

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Indexing from data structures

**Indexing** is a means by which we can access a subset of an array, matrix, vector, etc.

We can use square brackets `[]` in both languages to subset many data structures.

Always remember: rows before columns

A major difference between the two languages is the initial index. 
  
    + `Python` starts with zero and ends non-inclusive
        
    + `R` starts with one and ends inclusive

We can also index multiple rows or columns using `:`


## Indexing unordered structures

Lists in `R` and dictionaries in `Python` are unorderd and must be indexed by their *keys*.

&nbsp;

\begincols
  \begincol{.48\textwidth}
  
  To get an element in an `R` list, use dollarsign notation:
  
  `list$name1`
  
  &nbsp;
  
  `R` lists actually aren't unordered and so you can also use double brackets:
  
  `list[[1]]`
  
  \endcol
  \begincol{.48\textwidth}
  
  To get an element in a `Python` dictionary we use square brackets:
  
  &nbsp;
  
  `dict = {'key':'value'}`
  
  &nbsp;
  
  `dict['key']`
  
  \endcol
\endcols

## Control structures

Our programs can become much more flexible and powerful if the process can proceed in multiple directions depending on characteristics of the input data or other arguments.

Code that allows progression of the program among one of multiple possible paths are often called **control structures**.

We have seen one control structure when we used *for loops* in Unix.

*If-Else statements*, what SWC refers to as "making choices" is another example of a control structure.

## Making choices with If-Else statements

If-Else statements use logic tests to make context-dependent decisions.

&nbsp;

General syntax is:

if (logic test)

&nbsp; &nbsp; &nbsp; &nbsp; do some stuff

else

&nbsp; &nbsp; &nbsp; &nbsp; do some other stuff

## Making choices with If-Else statements

What about if we have three conditions?

&nbsp;

What if we have four conditions?

&nbsp;

What if we have a decision tree where three conditions are nested within each of two higher level conditions?

&nbsp;

What if we only care about the case where the logic test is true?

## Remind me of the syntax for If-Else statements...

## Remind me of the syntax for If-Else statements...

Both languages follow the general syntax:

&nbsp;

\begincols
  \begincol{.48\textwidth}
  
  `if(x==1){`
  
  &nbsp; &nbsp; `print("x is 1")`
  
  `}else if(x==2){`
  
  &nbsp; &nbsp; `print("x is 2")`
  
  `}else{`
  
  &nbsp; &nbsp; `print("x isn't 1 or 2")`
  
  `}`
  
  \endcol
  \begincol{.48\textwidth}
  
  `if x==1:`
  
  &nbsp; &nbsp; `print("x is 1")`
  
  `elif x==2:`
  
  &nbsp; &nbsp; `print("x is 2")`
  
  `else:`
  
  &nbsp; &nbsp; `print("x isn't 1 or 2")`
  
  \endcol
\endcols

## Logic tests

`x==1`

`x!=1`

`x>1`

`x<1`

`x>=1`

`x<=1`

&nbsp;

Python uses `and`/`or` to indicate more complex logic tests, but R uses `&`/`|`

## If-Else statements are most useful in loops

A loop allows us to use an If-Else statement to consider many different scenarios and evaluate the condition for each scenario.

&nbsp;

Remind me how loops worked in Unix...

## For loops in Python and R

For loops are conceptually similar regardless of the language, so you already know how to use them.

&nbsp;

You only need to know the specific syntax for your language!

&nbsp;

\begincols
  \begincol{.48\textwidth}
  
  `for(i in 1:10){`
  
  &nbsp; &nbsp; `do some stuff`
  
  `}`
  
  \endcol
  \begincol{.48\textwidth}
  
  `for i in xrange(0,10,1):`
  
  &nbsp; &nbsp; `do some stuff`
  
  \endcol
\endcols

## Practice with control structures

**Challenge**: Use  a `for loop` and `if-else` statement to calculate the sum of wages for males and females in `wages.csv`.

&nbsp;

&nbsp;

## Practice with control structures

**Challenge**: Use  a `for loop` and `if-else` statement to calculate the sum of wages for males and females in `wages.csv`.

&nbsp;

&nbsp;

**Challenge**: Adjust your code to use the `for loop` and `if-else` statement to calculate the sum and the mean of wages for males and females in `wages.csv`.

## Vectorized functions mean less looping for you!

In some languages, like `c` and `fortran`, for loops are the only way to apply transformations or functions to elements of a list. For example, to double the value held in each element of a list/vector one would need (in pseudo-code):

&nbsp; &nbsp; `for i in sequence(1 to length of vector)`

&nbsp; &nbsp; &nbsp; &nbsp; `vector[i]=vector[i]*2`

&nbsp;

Lucky for us many scripting languages, including `Python` and `R`, do not require a for loop in this setting. Rather they can use **vectorized functions**. This means that functions can be applied to each element of a vector/list or directly to a vector/list.

&nbsp;

## Vectorized functions mean less looping for you!

In some languages, like `c` and `fortran`, for loops are the only way to apply transformations or functions to elements of a list. For example, to double the value held in each element of a list/vector one would need (in pseudo-code):

&nbsp; &nbsp; `for i in sequence(1 to length of vector)`

&nbsp; &nbsp; &nbsp; &nbsp; `vector[i]=vector[i]*2`

&nbsp;

Lucky for us many scripting languages, including `Python` and `R`, do not require a for loop in this setting. Rather they can use **vectorized functions**. This means that functions can be applied to each element of a vector/list or directly to a vector/list.

&nbsp;

**Challenge**: Revise your code from the previous challenge to avoid using loops or if-else statements.